export const proposalConfig = {
  name: "Eniya",
  buildupLines: [
    "Asbri b9at haja wahda...",
    "W hadi machi promise",
    "hadi question liik.",
  ],
  questionLines: [
    "Eniya...",
    "Will you be my wife?",
    "F Denia w fel akhra?",
    "And for eternity? ❤️",
  ],
  yesLabel: "Yes. Today, tomorrow, and for eternity ❤️",
  noLabel: "No",
  noMessages: [
    "Are you sure? 👀",
    "Think about it again...",
    "That button seems suspicious.",
    "Wrong button 😂",
    "Nice try.",
    "Really? 😭",
    "After all those promises?!",
    "You're making me nervous...",
    "Don't do this to me 😭",
    "Okay... I'll pretend I didn't see that.",
    "Maybe your finger slipped?",
    "That's not the button I was hoping for.",
    "ENIYA 😭",
    "Please reconsider my application.",
    "I have prepared an entire website for this.",
    "You're really going to click NO after all that?! 😂",
    "Okay, dramatic pause... try again.",
    "I refuse to believe you meant that.",
    "One more chance? ❤️",
  ],
  celebrationLines: [
    "She said yes. ❤️",
    "Forever tebda lyoum.",
    "I choose you too for eternity.",
  ],
  finalMessage: {
    heading: "Eniya ❤️",
    body: [
      "You are not just the person I love.",
      "You are the person I want beside me for everything that comes next.",
    ],
    closing: "For eternity.",
  },
  revisitMessage: {
    heading: "❤️ Forever",
    body: "You said yes. And I still can't believe it.",
  },
};
